//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Background_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MembersData
    {
        [Required]
        [Display(Name ="登入帳號")]
        public string UserID { get; set; }
        [Required]
        [Display(Name = "密碼")]
        public string UserPassWord { get; set; }
        [Required]
        [Display(Name = "會員姓名")]
        public string UserName { get; set; }
        [Display(Name = "電話")]
        public string Phone { get; set; }
        [Display(Name = "地址")]
        public string Address { get; set; }
    }
}
